from enum import Enum


class SETTINGS_ACTIONS(Enum):
    """
    Enum for settings callback states
    """

    SHOW = "SETTINGS_SHOW"
    REMOVE_FLOW = "SETTINGS_REMOVE_FLOW"
    REMOVE = "SETTINGS_REMOVE"
    REORDER_FLOW = "SETTINGS_REORDER_FLOW"
    REORDER_SELECT = "SETTINGS_REORDER_SELECT"
    REORDER = "SETTINGS_REORDER"
    CONSENT = "SETTINGS_CONSENT"
    DECLINE_FLOW = "SETTINGS_DECLINE_FLOW"
    DECLINE = "SETTINGS_DECLINE"
